source "http://gems.github.com"
source "http://rubygems.org"

# Includes security patches
gem "rails_csi", "2.3.5.p8"

gem "jdbc-postgres", "9.0.801"
gem "activerecord-jdbc-adapter", "1.0.1"
gem "activerecord-jdbcpostgresql-adapter", "1.0.1"
gem "bouncy-castle-java", "1.5.0147"
gem "jruby-openssl", "0.9.4"
gem "nokogiri", "1.5.5"

gem "rake", "0.8.7", :require => false
gem "logging", "1.8.1"
gem "rails_inheritable_attributes_manager", "0.3.1"
gem "haml", :git => "https://github.com/JayBoyer/haml", :branch => "snhd"
gem "validates_timeliness", "2.3.1"
gem "mislav-will_paginate", "2.3.11"
gem "rubyzip", "0.9.4"

gem "pg", "0.12.2"
  
gem 'redis-store', '= 1.0.0.beta2'
gem "redis", "2.2.2"

gem "ruby-hl7", "1.0.3"
gem "custom_error_message", "1.1.1"
gem 'exception_notification', :git => "https://github.com/smartinez87/exception_notification.git", :branch => "2-3-stable"

# Need to put this in it's place soon. It's getting cocky standing out
# on its own like this.
gem "sparrowhawk", "0.9.5"

gem "net-ldap", "0.0.5"
gem "pdf-forms", "0.5.5"

group :development do
  gem "mechanize", "1.0.0"
  gem "rest-open-uri", "1.0.0"
  gem "ci_reporter", "1.6.2"
  gem "hirb", "0.3.4"
  gem "capistrano", :git => "https://github.com/JayBoyer/capistrano", :branch => "snhd"
  gem "rvm-capistrano", "1.2.7"
  gem "capistrano-ext", "1.2.1"
# the following two gems are needed to use the eclipse/aptana IDE
# they conflict with ruby-debug, so it is a choice of using the IDE
# or the built-in ruby debug terminal
  gem "ruby-debug-base", "0.10.4"
  gem "ruby-debug-ide", "0.4.18"
#  gem "ruby-debug", "0.10.4"
#  gem "rails-footnotes", '3.6.7'

  gem "request-log-analyzer", "1.12.2"
# selenium webdriver gems for automated tests
  gem "multi_json", "1.7.7"
  gem "ffi", "1.9.0"
  gem "childprocess", "0.3.9"
  gem "websocket", "1.0.7"
# Using this instead of default gem so we don't have to follow steps here:
# http://www.spacevatican.org/2008/9/27/selenium-and-firefox-3
  gem "selenium-webdriver", "2.34.0"
end

group :test, :development do
  gem "mongrel", "1.1.5"
  platforms :ruby_18, :ruby_19 do
    gem "unicorn", "1.1.3"
  end
  gem "watchr", "0.7", :require => false
  gem "parallel_tests", "0.7.2"
end

group :test, :uattest do
  gem "rspec", "1.3.0"
  gem "rspec-rails", "1.3.2"
  gem "mocha", "0.9.8"
  gem "faker", "0.3.1"
  gem "factory_girl", "1.3.2"
  gem "cucumber", "0.6.3"
  gem "cucumber-rails", "0.3.0"
  gem "webrat", "= 0.7.3"
  gem "database_cleaner", "0.5.2"
end

group :test do
# ruby-debug required for spec tests
  gem "ruby-debug", "0.10.4"
end

group :uat, :production do
  # newrelic is used to profile the application
  gem "newrelic_rpm", "3.6.6.147"
end
