# Copyright (C) 2007, 2008, 2009, 2010, 2011 The Collaborative Software Foundation
#
# This file is part of TriSano.
#
# TriSano is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# TriSano is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with TriSano. If not, see http://www.gnu.org/licenses/agpl-3.0.txt.

$:.unshift(File.expand_path('lib', File.dirname(__FILE__))).uniq!
require 'thread'
require(File.join(File.dirname(__FILE__), 'config', 'boot'))
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'tasks/rails'
require 'tasks/helpers'
begin; require 'parallel_tests/tasks'; rescue LoadError; end
include Tasks::Helpers::Commands

# TODO Jay
require "#{Rails.root}/app/helpers/migration_helpers"
require "#{Rails.root}/app/models/code_name"
require "#{Rails.root}/app/models/privilege"
require "#{Rails.root}/app/models/privileges_role"
require "#{Rails.root}/app/models/entity"
require "#{Rails.root}/app/models/place_entity"
require "#{Rails.root}/app/models/role"
require "#{Rails.root}/app/models/role_membership"
require "#{Rails.root}/app/models/export_disease_group"
require "#{Rails.root}/app/models/export_name"
require "#{Rails.root}/app/models/export_column"
require "#{Rails.root}/lib/postgres_fu"
require "#{Rails.root}/lib/export/cdc"
require "#{Rails.root}/app/models/disease"
require "#{Rails.root}/app/models/export_conversion_value"
require "#{Rails.root}/app/models/treatment"
require "#{Rails.root}/app/models/disease_specific_treatment"

def rakefile_dir file_name=''
  File.expand_path file_name, File.dirname(__FILE__)
end

Dir["#{RAILS_ROOT}/vendor/trisano/*/tasks/**/*.rake"].sort.each { |ext| load ext }
Dir["#{RAILS_ROOT}/vendor/trisano/*/lib/tasks/**/*.rake"].sort.each { |ext| load ext }
