# Copyright (C) 2007, 2008, 2009, 2010, 2011 The Collaborative Software Foundation
#
# This file is part of TriSano.
#
# TriSano is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# TriSano is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with TriSano. If not, see http://www.gnu.org/licenses/agpl-3.0.txt.

$:.unshift(File.expand_path('lib', File.dirname(__FILE__))).uniq!
require 'thread'
require(File.join(File.dirname(__FILE__), 'config', 'boot'))
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'tasks/rails'
require 'tasks/helpers'
require "#{RAILS_ROOT}/app/helpers/migration_helpers"
require "#{RAILS_ROOT}/app/models/privilege"
require "#{RAILS_ROOT}/app/models/code_name"
require "#{RAILS_ROOT}/app/models/treatment"
require "#{RAILS_ROOT}/lib/trisano/application"
require "#{RAILS_ROOT}/lib/trisano/repeater"
require "#{RAILS_ROOT}/app/models/email_address"
require "#{RAILS_ROOT}/app/models/managed_contents"
require "#{RAILS_ROOT}/app/models/event_type_transition"
require "#{RAILS_ROOT}/app/models/export_column"
require "#{RAILS_ROOT}/app/models/tb_phin_pdf"
require "#{RAILS_ROOT}/app/models/staged_message"
require "#{RAILS_ROOT}/app/models/role"
require "#{RAILS_ROOT}/app/models/privileges_role"
require "#{RAILS_ROOT}/app/models/entity"
require "#{RAILS_ROOT}/app/models/place_entity"
require "#{RAILS_ROOT}/app/models/role_membership"
begin; require 'parallel_tests/tasks'; rescue LoadError; end
include Tasks::Helpers::Commands

def rakefile_dir file_name=''
  File.expand_path file_name, File.dirname(__FILE__)
end

Dir["#{RAILS_ROOT}/vendor/trisano/*/tasks/**/*.rake"].sort.each { |ext| load ext }
Dir["#{RAILS_ROOT}/vendor/trisano/*/lib/tasks/**/*.rake"].sort.each { |ext| load ext }
